[characters]

# Function Row (Moons)
moon_full = 'ğŸŒ•'
moon_gibbous =  [ 'ğŸŒ–', 'ğŸŒ”' ]
moon_quarter =  [ 'ğŸŒ—', 'ğŸŒ“' ]
moon_crescent = [ 'ğŸŒ˜', 'ğŸŒ’' ]
moon_new =  'ğŸŒ‘'

# Number Row
rocket = 'ğŸš€'
dizzy = 'ğŸ’«'
fire = 'ğŸ”¥'
anger = 'ğŸ’¢'
heart = 'â¤ï¸'
tada = 'ğŸ‰'

# Upper Row (Faces)
laugh = [ 'ğŸ˜‚', 'ğŸ¤£' ]
smile = [ 'ğŸ™‚', 'ğŸ™ƒ' ]
eyes = [ 'ğŸ¤©', 'ğŸ˜' ]
joke = [ 'ğŸ˜‰', 'ğŸ˜œ' ]
fear = [ 'ğŸ˜¨', 'ğŸ˜±' ]
surprise = [ 'ğŸ¤¯', 'ğŸ˜µ' ]

# Home Row (Gestures)
attention = ['ğŸ›ï¸', 'ğŸ‘‹']
approval = [ 'ğŸ‘Œ', 'ğŸ˜' ]
gratitude = [ 'ğŸ™', 'ğŸ«¡' ]
anxiety = [ 'ğŸ˜…', 'ğŸ˜°' ]
despair = [ 'ğŸ˜', 'ğŸ˜¢' ]
curious = [ 'ğŸ¤”', 'ğŸ§' ]

## Lower Row (Status)
check = 'âœ…'
warn = 'âš ï¸'
x = 'âŒ'
question = 'â“'
megaphone = 'ğŸ“£'
siren = 'ğŸš¨'

# Bottom Row (Animals)
clown = 'ğŸ¤¡'
frog = 'ğŸ¸'
otter = 'ğŸ¦¦'
eagle = 'ğŸ¦…'
cricket = 'ğŸ¦—'

# Thumb Upper Arc (Fun)
king = ['ğŸ‘‘', 'ğŸ’ª']
sparks = ['âœ¨', 'ğŸ’¥']
sus = ['ğŸ˜', 'ğŸ‘€']

# Thumb Lower Arc (Thumbs)
point = [ 'â˜ï¸',  'ğŸ«µ' ]
hands = [ 'ğŸ™Œ', 'ğŸ‘' ]
thumbs = [ 'ğŸ‘', 'ğŸ‘' ]
