#
# Gitmoji
#
# This is a subset of the gitmoji specification.
# It contains the symbols that I use most. The whole spec
# would take up both halves of the board, and I don't use most
# of the specification anyway. I have left the ommitted symbols
# commented out so you can swap them in if you want.

[gitmoji.active]
# Function Row (Deployment Commits)
initial = 'ğŸ‰'
package = 'ğŸ“¦ï¸'
tags = 'ğŸ”–'
merge = 'ğŸ”€'
revert = 'âªï¸'

# Number Row (Debugging)
warnings = 'ğŸš¨'
failing_test = 'ğŸ§ª'
logs_add = 'ğŸ”Š'
logs_remove = 'ğŸ”‡'
experiments = 'âš—ï¸'
exploration = 'ğŸ§'

# Upper Row (Commit Types)
docs = 'ğŸ“'
comments = 'ğŸ’¡'
types = 'ğŸ·ï¸'
hotfix = 'ğŸš‘ï¸'
typeo = 'âœï¸'
wip = 'ğŸš§'

# Home Row (Common Commits)
performance = 'âš¡ï¸'
feature = 'âœ¨'
bug = 'ğŸ›'
remove = 'ğŸ”¥'
tests = 'âœ…'
structure = 'ğŸ¨'

# Lower Row (Configurations)
secrets = 'ğŸ”'
configs = 'ğŸ”§'
scripts = 'ğŸ”¨'
ignore = 'ğŸ™ˆ'
database = 'ğŸ—ƒï¸'
sponsor = 'ğŸ’¸'

# Bottom Row (Dependencies)
pin = 'ğŸ“Œ'
add_dep = 'â•'
remove_dep = 'â–'
upgrade = 'â¬†ï¸'
downgrade = 'â¬‡ï¸'

[gitmoji.inactive]
deploy = 'ğŸš€'
style = 'ğŸ’„'
security = 'ğŸ”’ï¸'
ci = 'ğŸ’š'
build_system = 'ğŸ‘·'
analytics = 'ğŸ“ˆ'
refactor = 'â™»ï¸'
i18n = 'ğŸŒ'
bad = 'ğŸ’©'
external = 'ğŸ‘½ï¸'
experience = 'ğŸ§‘â€ğŸ’»'
move = 'ğŸšš'
license = 'ğŸ“„'
breaking = 'ğŸ’¥'
assets = 'ğŸ±'
accessability = 'â™¿ï¸'
drunk = 'ğŸ»'
text = 'ğŸ’¬'
contributors = 'ğŸ‘¥'
ux = 'ğŸš¸'
architecture = 'ğŸ—ï¸'
responsive = 'ğŸ“±'
mock = 'ğŸ¤¡'
egg = 'ğŸ¥š'
snapshots = 'ğŸ“¸'
seo = 'ğŸ”ï¸'
seed = 'ğŸŒ±'
flags = 'ğŸš©'
catch = 'ğŸ¥…'
animations = 'ğŸ’«'
deprecate = 'ğŸ—‘ï¸'
auth = 'ğŸ›‚'
fix = 'ğŸ©¹'
dead_code = 'âš°ï¸'
business = 'ğŸ‘”'
health = 'ğŸ©º'
infra = 'ğŸ§±'
thread = 'ğŸ§µ'
validation = 'ğŸ¦º'

#
# Reactions
#

[reactions]
# Function Row (Time Symbols)
new_moon = 'ğŸŒ‘'
waxing_crescent_moon = 'ğŸŒ’'
first_quarter_moon = 'ğŸŒ“'
waxing_gibbous_moon = 'ğŸŒ”'
full_moon = 'ğŸŒ•'

# Number Row (Event Symbols)
rocket = 'ğŸš€'
fire = 'ğŸ”¥'
dizzy = 'ğŸ’«'
anger = 'ğŸ’¢'
heart = 'â¤ï¸'
tada = 'ğŸ‰'

# Upper Row (Negative Smiles)
think = 'ğŸ¤”'
shock = 'ğŸ˜±'
sweat = 'ğŸ˜°'
sad = 'ğŸ˜”'
neutral = 'ğŸ˜'
smirk = 'ğŸ˜'

# Home Row (Positive Smiles)
mind_blown = 'ğŸ¤¯'
lol = 'ğŸ˜‚'
sweat_smile = 'ğŸ˜…'
smile = 'ğŸ™‚'
party = 'ğŸ¥³'
cool = 'ğŸ˜'

# Lower Row (Status Symbols)
siren = 'ğŸš¨'
megaphone = 'ğŸ“£'
question = 'â“'
x = 'âŒ'
warn = 'âš ï¸'
check = 'âœ…'

# Bottom Row (Action Symbols)
crown = 'ğŸ‘‘'
strong = 'ğŸ’ª'
boom = 'ğŸ’¥'
sparkle = 'âœ¨'
look = 'ğŸ‘€'

# Thumb Cluster (Hands)
ok = 'ğŸ‘Œ'
up = 'â˜ï¸'
yes = 'ğŸ‘'
thanks = 'ğŸ™'
hands_raised = 'ğŸ™Œ'
no = 'ğŸ‘'
